version: '3'
services:
  db:
    image: mongo:latest
    ports:
      - "27017:27017"
    network_mode: "host"

  app:
    build: .
    depends_on:
      - db
    ports:
      - "8080:8080"
    network_mode: "host"